### ISSUE TITLE
PATH is an environment variable

### ISSUE THREAD

**Issue by mc-cat-tty** [ent0n29/compilers-assignments#15]
[testing.sh](first-assignment/testing.sh) makes use of `PATH` variable, which is a "reserved" environment variable for listing bin search directories, in POSIX and Unix-like systems.

A viable solution is to change its name to something different.

As an alternative, a relative path can be used, as long as the behaviour of the script is not altered. This is the preferred solution, implemented in 2c0dee43838234be4e21622fc20281c4f72bd73f commit.

**Comment by ent0n29** [comment]
$PATH was not meaned to be the "PATH" env variable, but just as a shortcut to say "path where you stored the file in your system". Was in charge of the user to change that line with its own path.
Better to change name to avoid ambiguity.

**Comment by ent0n29** [comment]
it had the same meaning of what prof. Marongiu uses as $ROOT/SRC/ecc...

**Comment by mc-cat-tty** [comment]
> $PATH was not meaned to be the "PATH" env variable, but just as a shortcut to say "path where you stored the file in your system". Was in charge of the user to change that line with its own path. Better to change name to avoid ambiguity.

Can auto-deduction be a good solution to avoid user interaction (9dfc647da94bf1d6ab618e39384ad03284c3f211)?

**Comment by ent0n29** [comment]
if it works then yes looool
