### ISSUE TITLE
Subtraction isn't commutative

### ISSUE THREAD

**Issue by mc-cat-tty** [ent0n29/compilers-assignments#18]
`optMultiInstr` doesn't take into account that subtraction is not a commutative operation.

The following snippet should highlight the issue:
```
%2 = add i32 10, %0
%3 = sub i32 10, %2
```

Is turned into:
```
%2 = add i32 10, %0
%3 = %0
```

However, `10 - %0 + 10` is equal to  `-%0`.

The same bug arose in:
```
%2 = sub i32 10, %0
%3 = add i32 10, %2
```

**Comment by ent0n29** [comment]
need to modify the `optMultiInstr` function to handle subtraction separately

**Comment by ent0n29** [comment]
we need to check that if we are in a sub, the operands need to be in correct order

**Comment by ent0n29** [comment]
we need to check that if we are in a sub, the operands need to be in correct order

**Comment by ent0n29** [comment]
are you sure? looks too simple

**Comment by ent0n29** [comment]
no wait, i saw only this commit f5dd7b00b79294d64dee7ad165407f15adcfac5b ahah, let me check all the changes

**Comment by mc-cat-tty** [comment]
> no wait, i saw only this commit [f5dd7b0](https://github.com/ent0n29/compilers-assignments/commit/f5dd7b00b79294d64dee7ad165407f15adcfac5b) ahah, let me check all the changes

All good?
