### ISSUE TITLE
Behavioural testing

### ISSUE THREAD

**Issue by mc-cat-tty** [ent0n29/compilers-assignments#20]
Additionally to asm code comparison (expected vs optimized), we may try to compare the functional behaviour of the optimized code as a "black box". This kind of test would ensure the neutrality of the optimization.

For instance, the following snippet:
```
%2 = add %0, 10
%3 = sub %2, 10
%4 = mul %3, 1
ret %4
```

Can be optimized to:
```
ret %0
```

Both the first and the second snippet, should behave the same, since the optimization generates a piece of code that is equivalent (but optimized).

**Comment by ent0n29** [comment]
_reading this from monte vangelo with a spritz in my hands_

**Comment by ent0n29** [comment]
yes, and i agree, but i think i didn't catch what is your suggestion
