### ISSUE TITLE
write tests for every optimization pass of the assignment

### ISSUE THREAD

**Issue by ent0n29** [ent0n29/compilers-assignments#4]
check first-assignment/tests dir, and write good .ll code to test our optimization passes.

**Comment by ent0n29** [comment]
test added with 12a500d62ea08389db4eaf29b3440d7f4f146be7, feedback on optimized versions needed

**Comment by mc-cat-tty** [comment]
Proposals:
 - [x] Bash/Python script for unit testing to avoid regression errors
 - [x] Needed from prev. point: an expected result for each test

**Comment by ent0n29** [comment]
> Proposals:
> 
> * [x]  Bash/Python script for unit testing to avoid regression errors
> * [x]  Needed from prev. point: an expected result for each test

@ch-fano can you help?

**Comment by ent0n29** [comment]
added automated test script with 27457ad7163786953c437519888b7489bee8c4d4
